export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ERROR = 'ERROR' 
export const GET_SINGLE_PRODUCT= 'GET_SINGLE_PRODUCT'

export const ADD_TO_CART ='ADD_TO_CART'

export const  REMOVE_CART_ITEM= 'REMOVE_CART_ITEM'
 export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'
 export const REMOVE_ONE = 'REMOVE_ONE'
 